env:
  browser: true
  es2021: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules:
  max-len:
    - 1
    - code: 120
  # https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb-base/rules/style.js#L340-L358
  no-restricted-syntax:
    - error
    - selector: ForInStatement
      message: >
        for..in loops iterate over the entire prototype chain, which is virtually never what you want.
        Use Object.{keys,values,entries}, and iterate over the resulting array.
    # Allow ForOfStatement syntax
    # - selector: 'ForOfStatement'
    #   message: 'iterators/generators require regenerator-runtime, which is too heavyweight for this guide to allow them. Separately, loops should be avoided in favor of array iterations.'
    - selector: LabeledStatement
      message: Labels are a form of GOTO; using them makes code confusing and hard to maintain and understand.
    - selector: WithStatement
      message: '`with` is disallowed in strict mode because it makes code impossible to predict and optimize.'
